accounts:
  - name: user0
    coins: ["1credit", "100000000stake"]
  - name: gt
    coins: ["1credit"]
  - name: faucet
    coins: ["21000000credit"]
validator:
  name: user0
  staked: "100000000stake"

