// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inventory/review.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Review struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id           uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	RecType      string `protobuf:"bytes,3,opt,name=recType,proto3" json:"recType,omitempty"`
	ItemId       string `protobuf:"bytes,4,opt,name=itemId,proto3" json:"itemId,omitempty"`
	ReviewerId   string `protobuf:"bytes,5,opt,name=reviewerId,proto3" json:"reviewerId,omitempty"`
	ReviewDetail string `protobuf:"bytes,6,opt,name=reviewDetail,proto3" json:"reviewDetail,omitempty"`
	ReviewDate   string `protobuf:"bytes,7,opt,name=reviewDate,proto3" json:"reviewDate,omitempty"`
	UpCount      string `protobuf:"bytes,8,opt,name=upCount,proto3" json:"upCount,omitempty"`
	DownCount    string `protobuf:"bytes,9,opt,name=downCount,proto3" json:"downCount,omitempty"`
	Status       string `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	LastDate     string `protobuf:"bytes,11,opt,name=lastDate,proto3" json:"lastDate,omitempty"`
}

func (m *Review) Reset()         { *m = Review{} }
func (m *Review) String() string { return proto.CompactTextString(m) }
func (*Review) ProtoMessage()    {}
func (*Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_405643e905c6084c, []int{0}
}
func (m *Review) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Review.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Review.Merge(m, src)
}
func (m *Review) XXX_Size() int {
	return m.Size()
}
func (m *Review) XXX_DiscardUnknown() {
	xxx_messageInfo_Review.DiscardUnknown(m)
}

var xxx_messageInfo_Review proto.InternalMessageInfo

func (m *Review) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Review) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Review) GetRecType() string {
	if m != nil {
		return m.RecType
	}
	return ""
}

func (m *Review) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *Review) GetReviewerId() string {
	if m != nil {
		return m.ReviewerId
	}
	return ""
}

func (m *Review) GetReviewDetail() string {
	if m != nil {
		return m.ReviewDetail
	}
	return ""
}

func (m *Review) GetReviewDate() string {
	if m != nil {
		return m.ReviewDate
	}
	return ""
}

func (m *Review) GetUpCount() string {
	if m != nil {
		return m.UpCount
	}
	return ""
}

func (m *Review) GetDownCount() string {
	if m != nil {
		return m.DownCount
	}
	return ""
}

func (m *Review) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Review) GetLastDate() string {
	if m != nil {
		return m.LastDate
	}
	return ""
}

func init() {
	proto.RegisterType((*Review)(nil), "jack139.artchain.inventory.Review")
}

func init() { proto.RegisterFile("inventory/review.proto", fileDescriptor_405643e905c6084c) }

var fileDescriptor_405643e905c6084c = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xb1, 0x6e, 0xf2, 0x30,
	0x1c, 0xc4, 0x71, 0x3e, 0xbe, 0x00, 0x6e, 0xd5, 0xc1, 0xaa, 0x90, 0x85, 0x2a, 0x0b, 0x31, 0xb1,
	0x34, 0x56, 0xc5, 0xd4, 0xb5, 0x45, 0xaa, 0x58, 0x51, 0xa7, 0x6e, 0x26, 0xb1, 0x82, 0x5b, 0x88,
	0x23, 0xe7, 0x1f, 0x68, 0xde, 0xa2, 0x0f, 0xd3, 0x87, 0xe8, 0xc8, 0xd8, 0xb1, 0x4a, 0x5e, 0xa4,
	0x8a, 0x1d, 0x08, 0xdd, 0xf2, 0xbb, 0xbb, 0xfc, 0x7d, 0xd2, 0xe1, 0xa1, 0x4a, 0x76, 0x32, 0x01,
	0x6d, 0x0a, 0x6e, 0xe4, 0x4e, 0xc9, 0x7d, 0x90, 0x1a, 0x0d, 0x9a, 0x8c, 0x5e, 0x45, 0xf8, 0x76,
	0x37, 0xbb, 0x0f, 0x84, 0x81, 0x70, 0x2d, 0x54, 0x12, 0x9c, 0x82, 0xa3, 0xeb, 0x58, 0xc7, 0xda,
	0xc6, 0x78, 0xfd, 0xe5, 0xfe, 0x98, 0x7c, 0x7a, 0xd8, 0x5f, 0xda, 0x13, 0x84, 0xe2, 0x5e, 0x68,
	0xa4, 0x00, 0x6d, 0x28, 0x1a, 0xa3, 0xe9, 0x60, 0x79, 0x44, 0x72, 0x85, 0x3d, 0x15, 0x51, 0x6f,
	0x8c, 0xa6, 0xdd, 0xa5, 0xa7, 0xa2, 0x3a, 0x69, 0x64, 0xf8, 0x5c, 0xa4, 0x92, 0xfe, 0x73, 0xc9,
	0x06, 0xc9, 0x10, 0xfb, 0x0a, 0xe4, 0x76, 0x11, 0xd1, 0xae, 0x35, 0x1a, 0x22, 0x0c, 0x63, 0x57,
	0x54, 0x9a, 0x45, 0x44, 0xff, 0x5b, 0xef, 0x4c, 0x21, 0x13, 0x7c, 0xe9, 0x68, 0x2e, 0x41, 0xa8,
	0x0d, 0xf5, 0x6d, 0xe2, 0x8f, 0xd6, 0xde, 0x98, 0x0b, 0x90, 0xb4, 0x77, 0x7e, 0xa3, 0x56, 0xea,
	0x56, 0x79, 0xfa, 0xa8, 0xf3, 0x04, 0x68, 0xdf, 0xb5, 0x6a, 0x90, 0xdc, 0xe0, 0x41, 0xa4, 0xf7,
	0x89, 0xf3, 0x06, 0xd6, 0x6b, 0x85, 0xba, 0x73, 0x06, 0x02, 0xf2, 0x8c, 0x62, 0xd7, 0xd9, 0x11,
	0x19, 0xe1, 0xfe, 0x46, 0x64, 0x60, 0x5f, 0xbb, 0xb0, 0xce, 0x89, 0x1f, 0x9e, 0xbe, 0x4a, 0x86,
	0x0e, 0x25, 0x43, 0x3f, 0x25, 0x43, 0x1f, 0x15, 0xeb, 0x1c, 0x2a, 0xd6, 0xf9, 0xae, 0x58, 0xe7,
	0xe5, 0x36, 0x56, 0xb0, 0xce, 0x57, 0x41, 0xa8, 0xb7, 0xbc, 0x59, 0x83, 0x1f, 0xd7, 0xe0, 0xef,
	0xbc, 0x1d, 0x0e, 0x8a, 0x54, 0x66, 0x2b, 0xdf, 0xce, 0x30, 0xfb, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x79, 0xa4, 0x53, 0x7d, 0xd2, 0x01, 0x00, 0x00,
}

func (m *Review) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Review) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Review) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LastDate) > 0 {
		i -= len(m.LastDate)
		copy(dAtA[i:], m.LastDate)
		i = encodeVarintReview(dAtA, i, uint64(len(m.LastDate)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintReview(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.DownCount) > 0 {
		i -= len(m.DownCount)
		copy(dAtA[i:], m.DownCount)
		i = encodeVarintReview(dAtA, i, uint64(len(m.DownCount)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.UpCount) > 0 {
		i -= len(m.UpCount)
		copy(dAtA[i:], m.UpCount)
		i = encodeVarintReview(dAtA, i, uint64(len(m.UpCount)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.ReviewDate) > 0 {
		i -= len(m.ReviewDate)
		copy(dAtA[i:], m.ReviewDate)
		i = encodeVarintReview(dAtA, i, uint64(len(m.ReviewDate)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ReviewDetail) > 0 {
		i -= len(m.ReviewDetail)
		copy(dAtA[i:], m.ReviewDetail)
		i = encodeVarintReview(dAtA, i, uint64(len(m.ReviewDetail)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ReviewerId) > 0 {
		i -= len(m.ReviewerId)
		copy(dAtA[i:], m.ReviewerId)
		i = encodeVarintReview(dAtA, i, uint64(len(m.ReviewerId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ItemId) > 0 {
		i -= len(m.ItemId)
		copy(dAtA[i:], m.ItemId)
		i = encodeVarintReview(dAtA, i, uint64(len(m.ItemId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.RecType) > 0 {
		i -= len(m.RecType)
		copy(dAtA[i:], m.RecType)
		i = encodeVarintReview(dAtA, i, uint64(len(m.RecType)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintReview(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintReview(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintReview(dAtA []byte, offset int, v uint64) int {
	offset -= sovReview(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Review) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovReview(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovReview(uint64(m.Id))
	}
	l = len(m.RecType)
	if l > 0 {
		n += 1 + l + sovReview(uint64(l))
	}
	l = len(m.ItemId)
	if l > 0 {
		n += 1 + l + sovReview(uint64(l))
	}
	l = len(m.ReviewerId)
	if l > 0 {
		n += 1 + l + sovReview(uint64(l))
	}
	l = len(m.ReviewDetail)
	if l > 0 {
		n += 1 + l + sovReview(uint64(l))
	}
	l = len(m.ReviewDate)
	if l > 0 {
		n += 1 + l + sovReview(uint64(l))
	}
	l = len(m.UpCount)
	if l > 0 {
		n += 1 + l + sovReview(uint64(l))
	}
	l = len(m.DownCount)
	if l > 0 {
		n += 1 + l + sovReview(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovReview(uint64(l))
	}
	l = len(m.LastDate)
	if l > 0 {
		n += 1 + l + sovReview(uint64(l))
	}
	return n
}

func sovReview(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozReview(x uint64) (n int) {
	return sovReview(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Review) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReview
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Review: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Review: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReview
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReview
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReview
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReview
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReview
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReview
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReview
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ItemId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReview
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReview
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReview
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ItemId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReviewerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReview
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReview
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReview
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReviewerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReviewDetail", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReview
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReview
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReview
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReviewDetail = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReviewDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReview
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReview
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReview
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReviewDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpCount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReview
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReview
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReview
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpCount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DownCount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReview
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReview
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReview
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DownCount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReview
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReview
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReview
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReview
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReview
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReview
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReview(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReview
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipReview(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowReview
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReview
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReview
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthReview
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupReview
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthReview
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthReview        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowReview          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupReview = fmt.Errorf("proto: unexpected end of group")
)
